### PR TITLE
Send FQDN on EHLO/HELO

### PR DESCRIPTION
**Pull request by ghost**
Some mail servers may reject a connection if there is no FQDN.

### CODE REVIEW

**Review by simsong — COMMENTED** [review]
Why are we sending *that* FQDN, rather than one of the current system?

**Comment by ghost** [comment]
Well, if I use tester at https://dane-test.had.dnsops.gov/, the tester connects with IP and IPv6 addresses, that their PTR points to dane-test.had.dnsops.gov.

I understand that it is hardcoded, but things like /home/slg are also, so I guess this tester is meant for https://dane-test.had.dnsops.gov/ only.

I may get the system's FQDN here, but I don't know if FQDN is set up on the https://dane-test.had.dnsops.gov/ machine.

If you think that I should get the system's FQDN instead of hardcoding, I will redo the pull request.

**Comment by simsong** [comment]
I haven’t worked on this project for a few years. I don’t like it being hard coded, though. It should probably be in a config file, even config.py. Could you do that?.


----
Sent from my phone.

> On Jan 7, 2020, at 10:47 PM, Evgeniy Khramtsov <notifications@github.com> wrote:
> 

﻿
Well, if I use tester at https://dane-test.had.dnsops.gov/, the tester connects with IP and IPv6 addresses, that their PTR points to dane-test.had.dnsops.gov.

I understand that it is hardcoded, but things like /home/slg are also, so I guess this tester is meant for https://dane-test.had.dnsops.gov/ only.

I may get the system's FQDN here, but I don't know if FQDN is set up on the https://dane-test.had.dnsops.gov/ machine.

If you think that I should get the system's FQDN instead of hardcoding, I will redo the pull request.

**Comment by ghost** [comment]
> It should probably be in a config file

I agree.

I could refactor things and put system-dependent things in the config, but such changes need to be tested by building the tester and running it.

Building the tester on a fresh CentOS 7 environment is complicated. I don't know why python33 is specified and why the tester uses an external OpenSSL, etc. I can't run a Makefile and expect it to build, and if I follow the steps by hand, the tester does not start because of various errors.

If I will find some spare free time and wish to build and refactor it, I will send my changes.

Also, about:

> I haven’t worked on this project for a few years

Does it mean that https://github.com/scottr-nist/dane_tester is the fork to submit pull requests?

**Comment by simsong** [comment]
Python33 was the most recent version of py try in available when I wrote this, and the external OpenSSL was used because the default didn’t include the necessary extensions. 


----
Sent from my phone.

> On Jan 7, 2020, at 11:21 PM, Evgeniy Khramtsov <notifications@github.com> wrote:
> 

﻿
It should probably be in a config file

I agree.

I could refactor things and put system-dependent things in the config, but such changes need to be tested by building the tester and running it.

Building the tester on a fresh CentOS 7 environment is complicated. I don't know why python33 is specified and why the tester uses an external OpenSSL, etc. I can't run a Makefile and expect it to build, and if I follow the steps by hand, the tester does not start because of various errors.

If I will find some spare free time and wish to build and refactor it, I will send my changes.

Also, about:

I haven’t worked on this project for a few years

Does it mean that https://github.com/scottr-nist/dane_tester is the fork to submit pull requests?

**Pull request closed without merging**
